phpfpm:
  image: alpine-php-fpm
  links:
   - mysql
  volumes:
    - .:/var/www/site/public
# hhvm:
#   image: diegomarangoni/hhvm:fastcgi
#   links:
#    - mysql
mysql:
  # command: mysqld --user=root --verbose
  image: mysql
  volumes:
    - .mysql:/var/lib/mysql
    - lowmem.cnf:/etc/mysql/conf.d/lowmem.cnf
  environment:
    MYSQL_DATABASE: database
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
nginx:
  image: alpine-nginx
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf
    - .:/var/www/site/public
  ports:
   - "8000:80"
  links:
   - phpfpm
